name: 'Generate GitHub Pages'
on:
  push:
    branches:
      - main
    paths:
      - '**.ird'
      - 'pages/**'
      - 'MetaGenerator/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    env:
      REPO_WEB_URL: '${{ github.server_url }}/${{ github.repository }}'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: Generate JSONs
        run: dotnet run --configuration Release --project MetaGenerator/MetaGenerator/MetaGenerator.csproj
      - name: Update base URL for scripts
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: '{{github.repo_web_url}}'
          replace: '${{ env.REPO_WEB_URL }}'
          regex: false
          include: 'pages/**.js'
      - name: Update branch name in scripts
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: '{{github.branch_name}}'
          replace: '${{ github.ref_name }}'
          regex: false
          include: 'pages/**.js'
      - name: Update commit hash in scripts
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: '{{github.sha}}'
          replace: '${{ github.sha }}'
          regex: false
          include: 'pages/**.js'
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'pages'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4